name: Nano
options:
  bundleIdPrefix: com.nano
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "15.0"
settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
    PRODUCT_BUNDLE_IDENTIFIER: com.nano.app
    MARKETING_VERSION: "1.0.1"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
targets:
  Nano:
    type: application
    platform: iOS
    sources:
      - Nano
    settings:
      base:
        INFOPLIST_FILE: Nano/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.nano.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTED_INTERFACE_ORIENTATIONS: "UIInterfaceOrientationPortrait"
